# Generated by Django 3.2.9 on 2022-03-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preference',
            field=models.CharField(default='일반', max_length=10),
        ),
    ]
