# Generated by Django 3.2.9 on 2022-03-28 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeekMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateField(default=datetime.date.today)),
                ('mealTime', models.IntegerField(default=0)),
                ('foodName', models.CharField(max_length=100)),
                ('foodCategory', models.CharField(max_length=100)),
                ('foodDetailCategory', models.CharField(max_length=100)),
                ('servingSize', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('foodKcal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sugar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carbohydrate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('protein', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cholesterol', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fattyAcid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.IntegerField(default=1)),
            ],
        ),
    ]
