# Generated by Django 4.0.3 on 2022-03-21 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=100)),
                ('foodCategory', models.CharField(max_length=100)),
                ('foodDetailCategory', models.CharField(max_length=100)),
                ('servingSize', models.IntegerField(default=1)),
                ('foodKcal', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('sugar', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('carbohydrate', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('protein', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('fat', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('cholesterol', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('fattyAcid', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('mealTime', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuToFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
    ]
