# Generated by Django 3.2.9 on 2022-03-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='meat',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='food',
            name='oily',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='food',
            name='seafood',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='food',
            name='spicy',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='food',
            name='vegetable',
            field=models.IntegerField(default=-1),
        ),
    ]
