# Generated by Django 3.2.9 on 2022-03-23 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_menu_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menutofood',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
