# Generated by Django 3.2.9 on 2022-03-31 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20220329_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodRecomm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodId', models.IntegerField(default=0)),
                ('foodName', models.CharField(max_length=100)),
                ('score', models.DecimalField(decimal_places=2, default=10, max_digits=4)),
            ],
        ),
    ]
