# Generated by Django 3.2.9 on 2022-03-24 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_alter_menutofood_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='date',
            new_name='dateTime',
        ),
    ]
