# Generated by Django 3.2.9 on 2022-03-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20220323_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='sugar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
